///************************************************
/// Generated by: DucVT
/// Date: 01/04/2014 02:15:37
/// Goal: Create User Service Class for DM_NHA_CUNG_CAP
///************************************************
/// <summary>
/// Create User Service Class for DM_NHA_CUNG_CAP
/// </summary>

using System;
using BKI_KHO.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_KHO.US{

public class US_DM_NHA_CUNG_CAP : US_Object
{
	private const string c_TableName = "DM_NHA_CUNG_CAP";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_NHA_CUNG_CAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_NHA_CUNG_CAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_NHA_CUNG_CAP"] = value;
		}
	}

	public bool IsMA_NHA_CUNG_CAPNull() 
	{
		return pm_objDR.IsNull("MA_NHA_CUNG_CAP");
	}

	public void SetMA_NHA_CUNG_CAPNull() {
		pm_objDR["MA_NHA_CUNG_CAP"] = System.Convert.DBNull;
	}

	public string strTEN_NHA_CUNG_CAP 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NHA_CUNG_CAP", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NHA_CUNG_CAP"] = value;
		}
	}

	public bool IsTEN_NHA_CUNG_CAPNull() 
	{
		return pm_objDR.IsNull("TEN_NHA_CUNG_CAP");
	}

	public void SetTEN_NHA_CUNG_CAPNull() {
		pm_objDR["TEN_NHA_CUNG_CAP"] = System.Convert.DBNull;
	}

	public decimal dcID_NHOM_NHA_CUNG_CAP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHOM_NHA_CUNG_CAP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHOM_NHA_CUNG_CAP"] = value;
		}
	}

	public bool IsID_NHOM_NHA_CUNG_CAPNull()	{
		return pm_objDR.IsNull("ID_NHOM_NHA_CUNG_CAP");
	}

	public void SetID_NHOM_NHA_CUNG_CAPNull() {
		pm_objDR["ID_NHOM_NHA_CUNG_CAP"] = System.Convert.DBNull;
	}

	public string strDIA_CHI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_CHI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_CHI"] = value;
		}
	}

	public bool IsDIA_CHINull() 
	{
		return pm_objDR.IsNull("DIA_CHI");
	}

	public void SetDIA_CHINull() {
		pm_objDR["DIA_CHI"] = System.Convert.DBNull;
	}

	public string strTEL 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEL", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEL"] = value;
		}
	}

	public bool IsTELNull() 
	{
		return pm_objDR.IsNull("TEL");
	}

	public void SetTELNull() {
		pm_objDR["TEL"] = System.Convert.DBNull;
	}

	public string strFAX 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "FAX", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["FAX"] = value;
		}
	}

	public bool IsFAXNull() 
	{
		return pm_objDR.IsNull("FAX");
	}

	public void SetFAXNull() {
		pm_objDR["FAX"] = System.Convert.DBNull;
	}

	public string strEMAIL 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "EMAIL", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["EMAIL"] = value;
		}
	}

	public bool IsEMAILNull() 
	{
		return pm_objDR.IsNull("EMAIL");
	}

	public void SetEMAILNull() {
		pm_objDR["EMAIL"] = System.Convert.DBNull;
	}

	public string strWEBSITE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "WEBSITE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["WEBSITE"] = value;
		}
	}

	public bool IsWEBSITENull() 
	{
		return pm_objDR.IsNull("WEBSITE");
	}

	public void SetWEBSITENull() {
		pm_objDR["WEBSITE"] = System.Convert.DBNull;
	}

	public string strMA_SO_THUE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_SO_THUE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_SO_THUE"] = value;
		}
	}

	public bool IsMA_SO_THUENull() 
	{
		return pm_objDR.IsNull("MA_SO_THUE");
	}

	public void SetMA_SO_THUENull() {
		pm_objDR["MA_SO_THUE"] = System.Convert.DBNull;
	}

	public string strNGUOI_DAI_DIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "NGUOI_DAI_DIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["NGUOI_DAI_DIEN"] = value;
		}
	}

	public bool IsNGUOI_DAI_DIENNull() 
	{
		return pm_objDR.IsNull("NGUOI_DAI_DIEN");
	}

	public void SetNGUOI_DAI_DIENNull() {
		pm_objDR["NGUOI_DAI_DIEN"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_NHA_CUNG_CAP() 
	{
		pm_objDS = new DS_DM_NHA_CUNG_CAP();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_NHA_CUNG_CAP(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_NHA_CUNG_CAP(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_NHA_CUNG_CAP();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
