///************************************************
/// Generated by: QUYETNT
/// Date: 19/05/2014 02:27:54
/// Goal: Create User Service Class for V_TRA_CUU_BAO_HANH
///************************************************
/// <summary>
/// Create User Service Class for V_TRA_CUU_BAO_HANH
/// </summary>

using System;
using BKI_KHO.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_KHO.US{

public class US_V_TRA_CUU_BAO_HANH : US_Object
{
	private const string c_TableName = "V_TRA_CUU_BAO_HANH";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_LOAI_CT 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_LOAI_CT", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_LOAI_CT"] = value;
		}
	}

	public bool IsMA_LOAI_CTNull() 
	{
		return pm_objDR.IsNull("MA_LOAI_CT");
	}

	public void SetMA_LOAI_CTNull() {
		pm_objDR["MA_LOAI_CT"] = System.Convert.DBNull;
	}

	public string strTEN_LOAI_CT 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_LOAI_CT", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_LOAI_CT"] = value;
		}
	}

	public bool IsTEN_LOAI_CTNull() 
	{
		return pm_objDR.IsNull("TEN_LOAI_CT");
	}

	public void SetTEN_LOAI_CTNull() {
		pm_objDR["TEN_LOAI_CT"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_CT 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_CT", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_CT"] = value;
		}
	}

	public bool IsID_LOAI_CTNull()	{
		return pm_objDR.IsNull("ID_LOAI_CT");
	}

	public void SetID_LOAI_CTNull() {
		pm_objDR["ID_LOAI_CT"] = System.Convert.DBNull;
	}

	public string strMA_CT 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_CT", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_CT"] = value;
		}
	}

	public bool IsMA_CTNull() 
	{
		return pm_objDR.IsNull("MA_CT");
	}

	public void SetMA_CTNull() {
		pm_objDR["MA_CT"] = System.Convert.DBNull;
	}

	public DateTime datNGAY_CT
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "NGAY_CT", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["NGAY_CT"] = value;
		}
	}

	public bool IsNGAY_CTNull()
	{
		return pm_objDR.IsNull("NGAY_CT");
	}

	public void SetNGAY_CTNull()
	{
		pm_objDR["NGAY_CT"] = System.Convert.DBNull;
	}

	public decimal dcID_CHUNG_TU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_CHUNG_TU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_CHUNG_TU"] = value;
		}
	}

	public bool IsID_CHUNG_TUNull()	{
		return pm_objDR.IsNull("ID_CHUNG_TU");
	}

	public void SetID_CHUNG_TUNull() {
		pm_objDR["ID_CHUNG_TU"] = System.Convert.DBNull;
	}

	public decimal dcID_HANG_HOA 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_HANG_HOA", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_HANG_HOA"] = value;
		}
	}

	public bool IsID_HANG_HOANull()	{
		return pm_objDR.IsNull("ID_HANG_HOA");
	}

	public void SetID_HANG_HOANull() {
		pm_objDR["ID_HANG_HOA"] = System.Convert.DBNull;
	}

	public decimal dcTHOI_GIAN_BH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THOI_GIAN_BH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THOI_GIAN_BH"] = value;
		}
	}

	public bool IsTHOI_GIAN_BHNull()	{
		return pm_objDR.IsNull("THOI_GIAN_BH");
	}

	public void SetTHOI_GIAN_BHNull() {
		pm_objDR["THOI_GIAN_BH"] = System.Convert.DBNull;
	}

	public decimal dcID_DVT_THOI_GIAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DVT_THOI_GIAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DVT_THOI_GIAN"] = value;
		}
	}

	public bool IsID_DVT_THOI_GIANNull()	{
		return pm_objDR.IsNull("ID_DVT_THOI_GIAN");
	}

	public void SetID_DVT_THOI_GIANNull() {
		pm_objDR["ID_DVT_THOI_GIAN"] = System.Convert.DBNull;
	}

	public decimal dcID_NHOM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHOM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHOM"] = value;
		}
	}

	public bool IsID_NHOMNull()	{
		return pm_objDR.IsNull("ID_NHOM");
	}

	public void SetID_NHOMNull() {
		pm_objDR["ID_NHOM"] = System.Convert.DBNull;
	}

	public string strMA_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_HANG"] = value;
		}
	}

	public bool IsMA_HANGNull() 
	{
		return pm_objDR.IsNull("MA_HANG");
	}

	public void SetMA_HANGNull() {
		pm_objDR["MA_HANG"] = System.Convert.DBNull;
	}

	public string strTEN_HANG_VN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_HANG_VN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_HANG_VN"] = value;
		}
	}

	public bool IsTEN_HANG_VNNull() 
	{
		return pm_objDR.IsNull("TEN_HANG_VN");
	}

	public void SetTEN_HANG_VNNull() {
		pm_objDR["TEN_HANG_VN"] = System.Convert.DBNull;
	}

	public decimal dcID_NHOM_CHA 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHOM_CHA", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHOM_CHA"] = value;
		}
	}

	public bool IsID_NHOM_CHANull()	{
		return pm_objDR.IsNull("ID_NHOM_CHA");
	}

	public void SetID_NHOM_CHANull() {
		pm_objDR["ID_NHOM_CHA"] = System.Convert.DBNull;
	}

	public string strTEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN"] = value;
		}
	}

	public bool IsTENNull() 
	{
		return pm_objDR.IsNull("TEN");
	}

	public void SetTENNull() {
		pm_objDR["TEN"] = System.Convert.DBNull;
	}

	public decimal dcExpr1 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "Expr1", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["Expr1"] = value;
		}
	}

	public bool IsExpr1Null()	{
		return pm_objDR.IsNull("Expr1");
	}

	public void SetExpr1Null() {
		pm_objDR["Expr1"] = System.Convert.DBNull;
	}

	public decimal dcExpr2 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "Expr2", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["Expr2"] = value;
		}
	}

	public bool IsExpr2Null()	{
		return pm_objDR.IsNull("Expr2");
	}

	public void SetExpr2Null() {
		pm_objDR["Expr2"] = System.Convert.DBNull;
	}

	public string strTEN_NHOM_HANG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NHOM_HANG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NHOM_HANG"] = value;
		}
	}

	public bool IsTEN_NHOM_HANGNull() 
	{
		return pm_objDR.IsNull("TEN_NHOM_HANG");
	}

	public void SetTEN_NHOM_HANGNull() {
		pm_objDR["TEN_NHOM_HANG"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_TRA_CUU_BAO_HANH() 
	{
		pm_objDS = new DS_V_TRA_CUU_BAO_HANH();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_TRA_CUU_BAO_HANH(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_TRA_CUU_BAO_HANH(decimal i_dbID) 
	{
		pm_objDS = new DS_V_TRA_CUU_BAO_HANH();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
