///************************************************
/// Generated by: TuyenNT
/// Date: 01/04/2014 09:54:38
/// Goal: Create Form for V_DM_HANG_HOA
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPSystemAdmin;

using BKI_KHO.US;
using BKI_KHO.DS;
using BKI_KHO.DS.CDBNames;

using C1.Win.C1FlexGrid;
using BKI_KHO.DanhMuc;

namespace BKI_KHO
{



	public class f300_V_DM_HANG_HOA : System.Windows.Forms.Form
    {
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
        private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
        private Panel m_pnl_top;
        private TextBox m_txt_tim_dm_hang_hoa;
        private TabControl m_tab_thong_tin_dm_hang_hoa;
        private TabPage tabPage1;
        private TextBox m_txt_don_vi;
        private Label m_lbl_don_vi;
        private TextBox m_txt_mo_ta;
        private Label m_lbl_mo_ta;
        private TextBox m_txt_gia_ban_le;
        private TextBox m_txt_gia_ban;
        private TextBox m_txt_gia_nhap;
        private Label m_lbl_gia_ban_le;
        private Label m_lbl_gia_ban;
        private Label m_lbl_gia_nhap;
        private TextBox m_txt_ten_hang_hoa;
        private TextBox m_txt_ma_hang_hoa;
        private Label m_lbl_ten_hang_hoa;
        private Label m_lbl_ma_hang_hoa;
        private TabPage tabPage2;
        private Label m_lbl_ma_vach;
        private TextBox m_txt_nha_cung_cap;
        private Label m_lbl_nha_cung_cap;
        private TextBox m_txt_nhom_goc;
        private Label m_lbl_nhom_goc;
        private TextBox m_txt_nhom;
        private Label m_lbl_nhom;
        private TextBox m_txt_ten_hang_hoa_en;
        private Label m_lbl_ten_hang_hoa_en;
        private Label m_lbl_1;
        private Label m_lbl_3;
        private Label m_lbl_thong_tin;
        private Label m_lbl_4;
        internal SIS.Controls.Button.SiSButton m_cmd_search;
        internal ImageList ImageList;
        internal SIS.Controls.Button.SiSButton m_cmd_insert;
        internal SIS.Controls.Button.SiSButton m_cmd_update;
        internal SIS.Controls.Button.SiSButton m_cmd_delete;
        internal SIS.Controls.Button.SiSButton m_cmd_exit;
        private PictureBox m_ptb_anh;
        internal ImageList imageList1;
		private System.ComponentModel.IContainer components;

		public f300_V_DM_HANG_HOA()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f300_V_DM_HANG_HOA));
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.m_pnl_top = new System.Windows.Forms.Panel();
            this.m_cmd_search = new SIS.Controls.Button.SiSButton();
            this.m_txt_tim_dm_hang_hoa = new System.Windows.Forms.TextBox();
            this.m_tab_thong_tin_dm_hang_hoa = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.m_ptb_anh = new System.Windows.Forms.PictureBox();
            this.m_txt_don_vi = new System.Windows.Forms.TextBox();
            this.m_lbl_don_vi = new System.Windows.Forms.Label();
            this.m_txt_mo_ta = new System.Windows.Forms.TextBox();
            this.m_lbl_mo_ta = new System.Windows.Forms.Label();
            this.m_txt_gia_ban_le = new System.Windows.Forms.TextBox();
            this.m_txt_gia_ban = new System.Windows.Forms.TextBox();
            this.m_txt_gia_nhap = new System.Windows.Forms.TextBox();
            this.m_lbl_gia_ban_le = new System.Windows.Forms.Label();
            this.m_lbl_gia_ban = new System.Windows.Forms.Label();
            this.m_lbl_gia_nhap = new System.Windows.Forms.Label();
            this.m_txt_ten_hang_hoa = new System.Windows.Forms.TextBox();
            this.m_txt_ma_hang_hoa = new System.Windows.Forms.TextBox();
            this.m_lbl_ten_hang_hoa = new System.Windows.Forms.Label();
            this.m_lbl_ma_hang_hoa = new System.Windows.Forms.Label();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.m_lbl_ma_vach = new System.Windows.Forms.Label();
            this.m_txt_nha_cung_cap = new System.Windows.Forms.TextBox();
            this.m_lbl_nha_cung_cap = new System.Windows.Forms.Label();
            this.m_txt_nhom_goc = new System.Windows.Forms.TextBox();
            this.m_lbl_nhom_goc = new System.Windows.Forms.Label();
            this.m_txt_nhom = new System.Windows.Forms.TextBox();
            this.m_lbl_nhom = new System.Windows.Forms.Label();
            this.m_txt_ten_hang_hoa_en = new System.Windows.Forms.TextBox();
            this.m_lbl_ten_hang_hoa_en = new System.Windows.Forms.Label();
            this.m_lbl_1 = new System.Windows.Forms.Label();
            this.m_lbl_3 = new System.Windows.Forms.Label();
            this.m_lbl_thong_tin = new System.Windows.Forms.Label();
            this.m_lbl_4 = new System.Windows.Forms.Label();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.m_pnl_top.SuspendLayout();
            this.m_tab_thong_tin_dm_hang_hoa.SuspendLayout();
            this.tabPage1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_ptb_anh)).BeginInit();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 507);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(1001, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(909, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 35;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(549, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(122, 28);
            this.m_cmd_insert.TabIndex = 34;
            this.m_cmd_insert.Text = "Thêm hàng hóa";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(671, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(122, 28);
            this.m_cmd_update.TabIndex = 33;
            this.m_cmd_update.Text = "Sửa hàng hóa";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(793, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(118, 28);
            this.m_cmd_delete.TabIndex = 32;
            this.m_cmd_delete.Text = "Xóa hàng hóa";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Location = new System.Drawing.Point(0, 59);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(1001, 245);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            this.m_fg.Click += new System.EventHandler(this.m_fg_Click);
            // 
            // m_pnl_top
            // 
            this.m_pnl_top.Controls.Add(this.m_cmd_search);
            this.m_pnl_top.Controls.Add(this.m_txt_tim_dm_hang_hoa);
            this.m_pnl_top.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_pnl_top.Location = new System.Drawing.Point(0, 0);
            this.m_pnl_top.Name = "m_pnl_top";
            this.m_pnl_top.Size = new System.Drawing.Size(1001, 53);
            this.m_pnl_top.TabIndex = 24;
            // 
            // m_cmd_search
            // 
            this.m_cmd_search.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_search.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_search.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_search.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_search.ImageIndex = 5;
            this.m_cmd_search.ImageList = this.ImageList;
            this.m_cmd_search.Location = new System.Drawing.Point(705, 12);
            this.m_cmd_search.Name = "m_cmd_search";
            this.m_cmd_search.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_search.TabIndex = 22;
            this.m_cmd_search.Text = "Tìm kiếm";
            // 
            // m_txt_tim_dm_hang_hoa
            // 
            this.m_txt_tim_dm_hang_hoa.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.m_txt_tim_dm_hang_hoa.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_txt_tim_dm_hang_hoa.Location = new System.Drawing.Point(218, 12);
            this.m_txt_tim_dm_hang_hoa.Name = "m_txt_tim_dm_hang_hoa";
            this.m_txt_tim_dm_hang_hoa.Size = new System.Drawing.Size(460, 26);
            this.m_txt_tim_dm_hang_hoa.TabIndex = 21;
            // 
            // m_tab_thong_tin_dm_hang_hoa
            // 
            this.m_tab_thong_tin_dm_hang_hoa.Controls.Add(this.tabPage1);
            this.m_tab_thong_tin_dm_hang_hoa.Controls.Add(this.tabPage2);
            this.m_tab_thong_tin_dm_hang_hoa.Location = new System.Drawing.Point(6, 347);
            this.m_tab_thong_tin_dm_hang_hoa.Name = "m_tab_thong_tin_dm_hang_hoa";
            this.m_tab_thong_tin_dm_hang_hoa.SelectedIndex = 0;
            this.m_tab_thong_tin_dm_hang_hoa.Size = new System.Drawing.Size(983, 160);
            this.m_tab_thong_tin_dm_hang_hoa.TabIndex = 31;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.m_ptb_anh);
            this.tabPage1.Controls.Add(this.m_txt_don_vi);
            this.tabPage1.Controls.Add(this.m_lbl_don_vi);
            this.tabPage1.Controls.Add(this.m_txt_mo_ta);
            this.tabPage1.Controls.Add(this.m_lbl_mo_ta);
            this.tabPage1.Controls.Add(this.m_txt_gia_ban_le);
            this.tabPage1.Controls.Add(this.m_txt_gia_ban);
            this.tabPage1.Controls.Add(this.m_txt_gia_nhap);
            this.tabPage1.Controls.Add(this.m_lbl_gia_ban_le);
            this.tabPage1.Controls.Add(this.m_lbl_gia_ban);
            this.tabPage1.Controls.Add(this.m_lbl_gia_nhap);
            this.tabPage1.Controls.Add(this.m_txt_ten_hang_hoa);
            this.tabPage1.Controls.Add(this.m_txt_ma_hang_hoa);
            this.tabPage1.Controls.Add(this.m_lbl_ten_hang_hoa);
            this.tabPage1.Controls.Add(this.m_lbl_ma_hang_hoa);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(975, 134);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Thông tin cơ bản";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // m_ptb_anh
            // 
            this.m_ptb_anh.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.m_ptb_anh.ErrorImage = ((System.Drawing.Image)(resources.GetObject("m_ptb_anh.ErrorImage")));
            this.m_ptb_anh.Location = new System.Drawing.Point(6, 6);
            this.m_ptb_anh.Name = "m_ptb_anh";
            this.m_ptb_anh.Size = new System.Drawing.Size(104, 118);
            this.m_ptb_anh.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.m_ptb_anh.TabIndex = 23;
            this.m_ptb_anh.TabStop = false;
            // 
            // m_txt_don_vi
            // 
            this.m_txt_don_vi.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_don_vi.Location = new System.Drawing.Point(233, 71);
            this.m_txt_don_vi.Name = "m_txt_don_vi";
            this.m_txt_don_vi.ReadOnly = true;
            this.m_txt_don_vi.Size = new System.Drawing.Size(68, 20);
            this.m_txt_don_vi.TabIndex = 16;
            // 
            // m_lbl_don_vi
            // 
            this.m_lbl_don_vi.AutoSize = true;
            this.m_lbl_don_vi.Location = new System.Drawing.Point(172, 74);
            this.m_lbl_don_vi.Name = "m_lbl_don_vi";
            this.m_lbl_don_vi.Size = new System.Drawing.Size(38, 13);
            this.m_lbl_don_vi.TabIndex = 15;
            this.m_lbl_don_vi.Text = "Đơn vị";
            // 
            // m_txt_mo_ta
            // 
            this.m_txt_mo_ta.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_mo_ta.Location = new System.Drawing.Point(717, 12);
            this.m_txt_mo_ta.Multiline = true;
            this.m_txt_mo_ta.Name = "m_txt_mo_ta";
            this.m_txt_mo_ta.ReadOnly = true;
            this.m_txt_mo_ta.Size = new System.Drawing.Size(252, 79);
            this.m_txt_mo_ta.TabIndex = 14;
            // 
            // m_lbl_mo_ta
            // 
            this.m_lbl_mo_ta.AutoSize = true;
            this.m_lbl_mo_ta.Location = new System.Drawing.Point(677, 43);
            this.m_lbl_mo_ta.Name = "m_lbl_mo_ta";
            this.m_lbl_mo_ta.Size = new System.Drawing.Size(34, 13);
            this.m_lbl_mo_ta.TabIndex = 13;
            this.m_lbl_mo_ta.Text = "Mô tả";
            // 
            // m_txt_gia_ban_le
            // 
            this.m_txt_gia_ban_le.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_gia_ban_le.Location = new System.Drawing.Point(534, 71);
            this.m_txt_gia_ban_le.Name = "m_txt_gia_ban_le";
            this.m_txt_gia_ban_le.ReadOnly = true;
            this.m_txt_gia_ban_le.Size = new System.Drawing.Size(122, 20);
            this.m_txt_gia_ban_le.TabIndex = 12;
            // 
            // m_txt_gia_ban
            // 
            this.m_txt_gia_ban.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_gia_ban.Location = new System.Drawing.Point(534, 40);
            this.m_txt_gia_ban.Name = "m_txt_gia_ban";
            this.m_txt_gia_ban.ReadOnly = true;
            this.m_txt_gia_ban.Size = new System.Drawing.Size(122, 20);
            this.m_txt_gia_ban.TabIndex = 11;
            // 
            // m_txt_gia_nhap
            // 
            this.m_txt_gia_nhap.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_gia_nhap.Location = new System.Drawing.Point(534, 12);
            this.m_txt_gia_nhap.Name = "m_txt_gia_nhap";
            this.m_txt_gia_nhap.ReadOnly = true;
            this.m_txt_gia_nhap.Size = new System.Drawing.Size(122, 20);
            this.m_txt_gia_nhap.TabIndex = 10;
            // 
            // m_lbl_gia_ban_le
            // 
            this.m_lbl_gia_ban_le.AutoSize = true;
            this.m_lbl_gia_ban_le.Location = new System.Drawing.Point(458, 74);
            this.m_lbl_gia_ban_le.Name = "m_lbl_gia_ban_le";
            this.m_lbl_gia_ban_le.Size = new System.Drawing.Size(55, 13);
            this.m_lbl_gia_ban_le.TabIndex = 9;
            this.m_lbl_gia_ban_le.Text = "Giá bán lẻ";
            // 
            // m_lbl_gia_ban
            // 
            this.m_lbl_gia_ban.AutoSize = true;
            this.m_lbl_gia_ban.Location = new System.Drawing.Point(469, 43);
            this.m_lbl_gia_ban.Name = "m_lbl_gia_ban";
            this.m_lbl_gia_ban.Size = new System.Drawing.Size(44, 13);
            this.m_lbl_gia_ban.TabIndex = 8;
            this.m_lbl_gia_ban.Text = "Giá bán";
            // 
            // m_lbl_gia_nhap
            // 
            this.m_lbl_gia_nhap.AutoSize = true;
            this.m_lbl_gia_nhap.Location = new System.Drawing.Point(463, 15);
            this.m_lbl_gia_nhap.Name = "m_lbl_gia_nhap";
            this.m_lbl_gia_nhap.Size = new System.Drawing.Size(50, 13);
            this.m_lbl_gia_nhap.TabIndex = 7;
            this.m_lbl_gia_nhap.Text = "Giá nhập";
            // 
            // m_txt_ten_hang_hoa
            // 
            this.m_txt_ten_hang_hoa.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_ten_hang_hoa.Location = new System.Drawing.Point(233, 40);
            this.m_txt_ten_hang_hoa.Name = "m_txt_ten_hang_hoa";
            this.m_txt_ten_hang_hoa.ReadOnly = true;
            this.m_txt_ten_hang_hoa.Size = new System.Drawing.Size(200, 20);
            this.m_txt_ten_hang_hoa.TabIndex = 6;
            // 
            // m_txt_ma_hang_hoa
            // 
            this.m_txt_ma_hang_hoa.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_ma_hang_hoa.Location = new System.Drawing.Point(233, 12);
            this.m_txt_ma_hang_hoa.Name = "m_txt_ma_hang_hoa";
            this.m_txt_ma_hang_hoa.ReadOnly = true;
            this.m_txt_ma_hang_hoa.Size = new System.Drawing.Size(111, 20);
            this.m_txt_ma_hang_hoa.TabIndex = 5;
            // 
            // m_lbl_ten_hang_hoa
            // 
            this.m_lbl_ten_hang_hoa.AutoSize = true;
            this.m_lbl_ten_hang_hoa.Location = new System.Drawing.Point(136, 43);
            this.m_lbl_ten_hang_hoa.Name = "m_lbl_ten_hang_hoa";
            this.m_lbl_ten_hang_hoa.Size = new System.Drawing.Size(74, 13);
            this.m_lbl_ten_hang_hoa.TabIndex = 2;
            this.m_lbl_ten_hang_hoa.Text = "Tên hàng hóa";
            // 
            // m_lbl_ma_hang_hoa
            // 
            this.m_lbl_ma_hang_hoa.AutoSize = true;
            this.m_lbl_ma_hang_hoa.BackColor = System.Drawing.SystemColors.Control;
            this.m_lbl_ma_hang_hoa.Location = new System.Drawing.Point(140, 15);
            this.m_lbl_ma_hang_hoa.Name = "m_lbl_ma_hang_hoa";
            this.m_lbl_ma_hang_hoa.Size = new System.Drawing.Size(70, 13);
            this.m_lbl_ma_hang_hoa.TabIndex = 1;
            this.m_lbl_ma_hang_hoa.Text = "Mã hàng hóa";
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.m_lbl_ma_vach);
            this.tabPage2.Controls.Add(this.m_txt_nha_cung_cap);
            this.tabPage2.Controls.Add(this.m_lbl_nha_cung_cap);
            this.tabPage2.Controls.Add(this.m_txt_nhom_goc);
            this.tabPage2.Controls.Add(this.m_lbl_nhom_goc);
            this.tabPage2.Controls.Add(this.m_txt_nhom);
            this.tabPage2.Controls.Add(this.m_lbl_nhom);
            this.tabPage2.Controls.Add(this.m_txt_ten_hang_hoa_en);
            this.tabPage2.Controls.Add(this.m_lbl_ten_hang_hoa_en);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(975, 134);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Thông tin bổ sung";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // m_lbl_ma_vach
            // 
            this.m_lbl_ma_vach.AutoSize = true;
            this.m_lbl_ma_vach.Location = new System.Drawing.Point(838, 17);
            this.m_lbl_ma_vach.Name = "m_lbl_ma_vach";
            this.m_lbl_ma_vach.Size = new System.Drawing.Size(49, 13);
            this.m_lbl_ma_vach.TabIndex = 13;
            this.m_lbl_ma_vach.Text = "Mã vạch";
            // 
            // m_txt_nha_cung_cap
            // 
            this.m_txt_nha_cung_cap.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_nha_cung_cap.Location = new System.Drawing.Point(493, 49);
            this.m_txt_nha_cung_cap.Name = "m_txt_nha_cung_cap";
            this.m_txt_nha_cung_cap.ReadOnly = true;
            this.m_txt_nha_cung_cap.Size = new System.Drawing.Size(176, 20);
            this.m_txt_nha_cung_cap.TabIndex = 12;
            // 
            // m_lbl_nha_cung_cap
            // 
            this.m_lbl_nha_cung_cap.AutoSize = true;
            this.m_lbl_nha_cung_cap.Location = new System.Drawing.Point(382, 52);
            this.m_lbl_nha_cung_cap.Name = "m_lbl_nha_cung_cap";
            this.m_lbl_nha_cung_cap.Size = new System.Drawing.Size(75, 13);
            this.m_lbl_nha_cung_cap.TabIndex = 11;
            this.m_lbl_nha_cung_cap.Text = "Nhà cung cấp";
            // 
            // m_txt_nhom_goc
            // 
            this.m_txt_nhom_goc.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_nhom_goc.Location = new System.Drawing.Point(114, 49);
            this.m_txt_nhom_goc.Name = "m_txt_nhom_goc";
            this.m_txt_nhom_goc.ReadOnly = true;
            this.m_txt_nhom_goc.Size = new System.Drawing.Size(176, 20);
            this.m_txt_nhom_goc.TabIndex = 10;
            // 
            // m_lbl_nhom_goc
            // 
            this.m_lbl_nhom_goc.AutoSize = true;
            this.m_lbl_nhom_goc.Location = new System.Drawing.Point(24, 52);
            this.m_lbl_nhom_goc.Name = "m_lbl_nhom_goc";
            this.m_lbl_nhom_goc.Size = new System.Drawing.Size(56, 13);
            this.m_lbl_nhom_goc.TabIndex = 9;
            this.m_lbl_nhom_goc.Text = "Nhóm gốc";
            // 
            // m_txt_nhom
            // 
            this.m_txt_nhom.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_nhom.Location = new System.Drawing.Point(114, 14);
            this.m_txt_nhom.Name = "m_txt_nhom";
            this.m_txt_nhom.ReadOnly = true;
            this.m_txt_nhom.Size = new System.Drawing.Size(176, 20);
            this.m_txt_nhom.TabIndex = 8;
            // 
            // m_lbl_nhom
            // 
            this.m_lbl_nhom.AutoSize = true;
            this.m_lbl_nhom.Location = new System.Drawing.Point(45, 17);
            this.m_lbl_nhom.Name = "m_lbl_nhom";
            this.m_lbl_nhom.Size = new System.Drawing.Size(35, 13);
            this.m_lbl_nhom.TabIndex = 7;
            this.m_lbl_nhom.Text = "Nhóm";
            // 
            // m_txt_ten_hang_hoa_en
            // 
            this.m_txt_ten_hang_hoa_en.BackColor = System.Drawing.SystemColors.Info;
            this.m_txt_ten_hang_hoa_en.Location = new System.Drawing.Point(493, 14);
            this.m_txt_ten_hang_hoa_en.Name = "m_txt_ten_hang_hoa_en";
            this.m_txt_ten_hang_hoa_en.ReadOnly = true;
            this.m_txt_ten_hang_hoa_en.Size = new System.Drawing.Size(189, 20);
            this.m_txt_ten_hang_hoa_en.TabIndex = 6;
            // 
            // m_lbl_ten_hang_hoa_en
            // 
            this.m_lbl_ten_hang_hoa_en.AutoSize = true;
            this.m_lbl_ten_hang_hoa_en.Location = new System.Drawing.Point(342, 17);
            this.m_lbl_ten_hang_hoa_en.Name = "m_lbl_ten_hang_hoa_en";
            this.m_lbl_ten_hang_hoa_en.Size = new System.Drawing.Size(121, 13);
            this.m_lbl_ten_hang_hoa_en.TabIndex = 2;
            this.m_lbl_ten_hang_hoa_en.Text = "Tên hàng hóa tiếng anh";
            // 
            // m_lbl_1
            // 
            this.m_lbl_1.AutoSize = true;
            this.m_lbl_1.Location = new System.Drawing.Point(13, 317);
            this.m_lbl_1.Name = "m_lbl_1";
            this.m_lbl_1.Size = new System.Drawing.Size(137, 13);
            this.m_lbl_1.TabIndex = 32;
            this.m_lbl_1.Text = "Thông tin chi tiết hàng hóa:";
            // 
            // m_lbl_3
            // 
            this.m_lbl_3.AutoSize = true;
            this.m_lbl_3.Location = new System.Drawing.Point(394, 317);
            this.m_lbl_3.Name = "m_lbl_3";
            this.m_lbl_3.Size = new System.Drawing.Size(76, 13);
            this.m_lbl_3.TabIndex = 33;
            this.m_lbl_3.Text = "Mã hàng hóa: ";
            // 
            // m_lbl_thong_tin
            // 
            this.m_lbl_thong_tin.AutoSize = true;
            this.m_lbl_thong_tin.Location = new System.Drawing.Point(156, 317);
            this.m_lbl_thong_tin.Name = "m_lbl_thong_tin";
            this.m_lbl_thong_tin.Size = new System.Drawing.Size(16, 13);
            this.m_lbl_thong_tin.TabIndex = 34;
            this.m_lbl_thong_tin.Text = "...";
            // 
            // m_lbl_4
            // 
            this.m_lbl_4.AutoSize = true;
            this.m_lbl_4.Location = new System.Drawing.Point(488, 317);
            this.m_lbl_4.Name = "m_lbl_4";
            this.m_lbl_4.Size = new System.Drawing.Size(16, 13);
            this.m_lbl_4.TabIndex = 35;
            this.m_lbl_4.Text = "...";
            // 
            // imageList1
            // 
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "");
            this.imageList1.Images.SetKeyName(1, "");
            this.imageList1.Images.SetKeyName(2, "");
            this.imageList1.Images.SetKeyName(3, "");
            this.imageList1.Images.SetKeyName(4, "");
            this.imageList1.Images.SetKeyName(5, "");
            this.imageList1.Images.SetKeyName(6, "");
            this.imageList1.Images.SetKeyName(7, "");
            this.imageList1.Images.SetKeyName(8, "");
            this.imageList1.Images.SetKeyName(9, "");
            this.imageList1.Images.SetKeyName(10, "");
            this.imageList1.Images.SetKeyName(11, "");
            this.imageList1.Images.SetKeyName(12, "");
            this.imageList1.Images.SetKeyName(13, "");
            this.imageList1.Images.SetKeyName(14, "");
            this.imageList1.Images.SetKeyName(15, "");
            this.imageList1.Images.SetKeyName(16, "");
            this.imageList1.Images.SetKeyName(17, "");
            this.imageList1.Images.SetKeyName(18, "");
            this.imageList1.Images.SetKeyName(19, "");
            this.imageList1.Images.SetKeyName(20, "");
            this.imageList1.Images.SetKeyName(21, "");
            // 
            // f300_V_DM_HANG_HOA
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(1001, 543);
            this.Controls.Add(this.m_lbl_4);
            this.Controls.Add(this.m_lbl_thong_tin);
            this.Controls.Add(this.m_lbl_3);
            this.Controls.Add(this.m_lbl_1);
            this.Controls.Add(this.m_tab_thong_tin_dm_hang_hoa);
            this.Controls.Add(this.m_pnl_top);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.MinimumSize = new System.Drawing.Size(1017, 582);
            this.Name = "f300_V_DM_HANG_HOA";
            this.Text = "f300_V_DM_HANG_HOA";
            this.Load += new System.EventHandler(this.f300_V_DM_HANG_HOA_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.m_pnl_top.ResumeLayout(false);
            this.m_pnl_top.PerformLayout();
            this.m_tab_thong_tin_dm_hang_hoa.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_ptb_anh)).EndInit();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
		#endregion

		#region Data Structure
		private enum e_col_Number{
			GIA_BAN = 6
,MA_HANG = 1
,TEN_HANG_VN = 2
,TEN_HANG_EN = 4
,MO_TA = 8
,DON_VI = 3
,GIA_BAN_LE = 7
,GIA_NHAP = 5

		}			
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_V_DM_HANG_HOA m_ds = new DS_V_DM_HANG_HOA();
		US_V_DM_HANG_HOA m_us = new US_V_DM_HANG_HOA();
		#endregion

		#region Private Methods
		private void format_controls(){
			CControlFormat.setFormStyle(this, new CAppContext_201());
			CControlFormat.setC1FlexFormat(m_fg);
			CGridUtils.AddSave_Excel_Handlers(m_fg);
            			CGridUtils.AddSearch_Handlers(m_fg);
			set_define_events();
			this.KeyPreview = true;		
		}
		private void set_initial_form_load(){						
			m_obj_trans = get_trans_object(m_fg);
			load_data_2_grid();		
		}	
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(V_DM_HANG_HOA.GIA_BAN, e_col_Number.GIA_BAN);
			v_htb.Add(V_DM_HANG_HOA.MA_HANG, e_col_Number.MA_HANG);
			v_htb.Add(V_DM_HANG_HOA.TEN_HANG_VN, e_col_Number.TEN_HANG_VN);
			v_htb.Add(V_DM_HANG_HOA.TEN_HANG_EN, e_col_Number.TEN_HANG_EN);
			v_htb.Add(V_DM_HANG_HOA.MO_TA, e_col_Number.MO_TA);
			v_htb.Add(V_DM_HANG_HOA.DON_VI, e_col_Number.DON_VI);
			v_htb.Add(V_DM_HANG_HOA.GIA_BAN_LE, e_col_Number.GIA_BAN_LE);
			//v_htb.Add(V_DM_HANG_HOA.IMAGE, e_col_Number.IMAGE);
			v_htb.Add(V_DM_HANG_HOA.GIA_NHAP, e_col_Number.GIA_NHAP);
									
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.V_DM_HANG_HOA.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(){						
			m_ds = new DS_V_DM_HANG_HOA();			
			m_us.FillDataset(m_ds);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
			m_fg.Redraw = true;
		}
		private void grid2us_object(US_V_DM_HANG_HOA i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

	
		private void us_object2grid(US_V_DM_HANG_HOA i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}


        //private void insert_v_dm_hang_hoa(){					    
        //}

		private void update_v_dm_hang_hoa(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
			grid2us_object(m_us, m_fg.Row);
		//	f300_V_DM_HANG_HOA_DE v_fDE = new f300_V_DM_HANG_HOA_DE();
		//	v_fDE.display(m_us);
			load_data_2_grid();
		}
				
		private void delete_v_dm_hang_hoa(){
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
			US_V_DM_HANG_HOA v_us = new US_V_DM_HANG_HOA();
			grid2us_object(v_us, m_fg.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_v_dm_hang_hoa(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us, m_fg.Row);
		//	f300_V_DM_HANG_HOA_DE v_fDE = new f300_V_DM_HANG_HOA_DE();			
		//	v_fDE.display(m_us);
		}
		private void set_define_events(){
			m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
			m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
			m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
			m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
			//m_cmd_view.Click += new EventHandler(m_cmd_view_Click);
		}
		#endregion

//
		//
		//		EVENT HANLDERS
		//
		//
		private void f300_V_DM_HANG_HOA_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		
		}

		private void m_cmd_exit_Click(object sender, EventArgs e)
        {
            this.Close();
        }

		private void m_cmd_insert_Click(object sender, EventArgs e) {
			try{
				insert_dm_hang_hoa();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

        private void insert_dm_hang_hoa()
        {
            f300_V_DM_HANG_HOA_DE v_fDE = new f300_V_DM_HANG_HOA_DE();
            v_fDE.display_for_insert();
            load_data_2_grid();
        }

		private void m_cmd_update_Click(object sender, EventArgs e) {
			try{
				update_dm_hang_hoa();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

        private void update_dm_hang_hoa()
        {
            f300_V_DM_HANG_HOA_DE v_fDE = new f300_V_DM_HANG_HOA_DE();
            v_fDE.display_for_update(m_us);
            load_data_2_grid();
        }

		private void m_cmd_delete_Click(object sender, EventArgs e) {
			try{
				delete_v_dm_hang_hoa();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_view_Click(object sender, EventArgs e) {
			try{
				view_v_dm_hang_hoa();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

        private void m_fg_Click(object sender, EventArgs e)
        {
            if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
            if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
            grid2us_object(m_us, m_fg.Row);

            m_lbl_thong_tin.Text = m_us.strTEN_HANG_VN;
            m_lbl_4.Text = m_us.strMA_HANG;
            m_txt_ma_hang_hoa.Text = m_us.strMA_HANG;
            m_txt_ten_hang_hoa.Text = m_us.strTEN_HANG_VN;
            m_txt_don_vi.Text = m_us.strDON_VI;
            if (m_us.dcGIA_BAN != null)
            {
                m_txt_gia_ban.Text = CIPConvert.ToStr(m_us.dcGIA_BAN);
            }
            else
            {
                m_txt_gia_ban.Text = "";
            }
            if (m_us.dcGIA_NHAP != null)
            {
                m_txt_gia_nhap.Text = CIPConvert.ToStr(m_us.dcGIA_NHAP);
            }
            else
            {
                m_txt_gia_nhap.Text = "";
            }
            if (m_us.dcGIA_BAN_LE != null)
            {
                m_txt_gia_ban_le.Text = CIPConvert.ToStr(m_us.dcGIA_BAN_LE);
            }
            else
            {
                m_txt_gia_ban_le.Text = "";
            }
            m_txt_mo_ta.Text = m_us.strMO_TA;

        }
	}
}

