///************************************************
/// Generated by: TONGDV
/// Date: 03/04/2014 04:46:50
/// Goal: Create User Service Class for DM_KHO
///************************************************
/// <summary>
/// Create User Service Class for DM_KHO
/// </summary>

using System;
using BKI_KHO.DS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;



namespace BKI_KHO.US{

public class US_DM_KHO : US_Object
{
	private const string c_TableName = "DM_KHO";
#region "Public Properties"
	public decimal dcID_KHO 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_KHO", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_KHO"] = value;
		}
	}

	public bool IsID_KHONull()	{
		return pm_objDR.IsNull("ID_KHO");
	}

	public void SetID_KHONull() {
		pm_objDR["ID_KHO"] = System.Convert.DBNull;
	}

	public string strMA_KHO 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_KHO", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_KHO"] = value;
		}
	}

	public bool IsMA_KHONull() 
	{
		return pm_objDR.IsNull("MA_KHO");
	}

	public void SetMA_KHONull() {
		pm_objDR["MA_KHO"] = System.Convert.DBNull;
	}

	public string strTEN_KHO 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_KHO", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_KHO"] = value;
		}
	}

	public bool IsTEN_KHONull() 
	{
		return pm_objDR.IsNull("TEN_KHO");
	}

	public void SetTEN_KHONull() {
		pm_objDR["TEN_KHO"] = System.Convert.DBNull;
	}

	public string strDIA_CHI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIA_CHI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIA_CHI"] = value;
		}
	}

	public bool IsDIA_CHINull() 
	{
		return pm_objDR.IsNull("DIA_CHI");
	}

	public void SetDIA_CHINull() {
		pm_objDR["DIA_CHI"] = System.Convert.DBNull;
	}

	public string strDIEN_THOAI 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DIEN_THOAI", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DIEN_THOAI"] = value;
		}
	}

	public bool IsDIEN_THOAINull() 
	{
		return pm_objDR.IsNull("DIEN_THOAI");
	}

	public void SetDIEN_THOAINull() {
		pm_objDR["DIEN_THOAI"] = System.Convert.DBNull;
	}

	public decimal dcID_NHAN_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NHAN_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NHAN_VIEN"] = value;
		}
	}

	public bool IsID_NHAN_VIENNull()	{
		return pm_objDR.IsNull("ID_NHAN_VIEN");
	}

	public void SetID_NHAN_VIENNull() {
		pm_objDR["ID_NHAN_VIEN"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_DM_KHO() 
	{
		pm_objDS = new DS_DM_KHO();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_DM_KHO(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_DM_KHO(decimal i_dbID) 
	{
		pm_objDS = new DS_DM_KHO();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
